# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListRandomPeople' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListRandomPeople
  pod 'lottie-ios'

  target 'ListRandomPeopleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListRandomPeopleUITests' do
    # Pods for testing
  end

end
